// Firebase Configuration
const firebaseConfig = {
    apiKey: "AIzaSyBsLraW-VGSZuDaqYWzrrBBlaWYWOat2t8",
    authDomain: "sponsor-job.firebaseapp.com",
    databaseURL: "https://sponsor-job-default-rtdb.firebaseio.com",
    projectId: "sponsor-job",
    storageBucket: "sponsor-job.firebasestorage.app",
    messagingSenderId: "476816277996",
    appId: "1:476816277996:web:32bd3e0c21e467e24180c9",
};

// Encryption Key
const ENCRYPTION_KEY = "EarningAppSecureKey2024!@#";

// Language Dictionary
const dict = {
    en: { 
        dashboard: "Dashboard", 
        task: "Task", 
        plan: "Plan", 
        withdraw: "Withdraw", 
        history: "History", 
        profile: "Profile", 
        rules: "Rules", 
        privacy_policy: "Privacy Policy",
        gift_code: "Gift Code",
        login: "Login", 
        logout: "Logout", 
        welcome: "Welcome", 
        activate: "Activate Account", 
        verified: "Verified", 
        inactive: "Inactive", 
        balance: "Balance", 
        income: "Total Income", 
        ref: "Referrals", 
        share: "Share & Earn", 
        guest: "Guest", 
        no_access: "Login Required", 
        no_access_desc: "Please login to access this feature.", 
        act_desc: "Activate to unlock Withdraw & Plans", 
        act_msg: "Account Inactive", 
        edit: "Edit", 
        save: "Save", 
        cancel: "Cancel", 
        trx_id: "Transaction ID", 
        submit: "Submit",
        logout_confirm: "Are you sure you want to logout?", 
        edit_profile: "Edit Profile",
        create_acc: "Create Account", 
        already_purchased: "Already Purchased", 
        buy_now: "Buy Now",
        loading_rec: "Loading records...", 
        no_rec: "No Records Found", 
        no_withdraw: "No Withdrawals Found",
        allow_popup: "Allow Popups", 
        task_complete: "Task Complete!", 
        insuff_bal: "Insufficient Balance!",
        login_title: "Login", 
        register_title: "Create Account", 
        login_ph: "Email Address", 
        pass_ph: "Password", 
        full_name_ph: "Full Name", 
        username_ph: "Username", 
        email_ph: "Email Address", 
        ref_ph: "Referral Code (Optional)", 
        confirm_ph: "Confirm Password",
        next: "Next", 
        back: "Back", 
        create_acc_btn: "Create Account", 
        no_account: "Don't have an account?", 
        have_account: "Already have an account?",
        register_link: "Register", 
        login_link: "Login",
        select_method: "Select Method", 
        send_money: "Send Money To", 
        method_bkash: "Bkash", 
        method_nagad: "Nagad",
        daily_claim: "Daily Claim", 
        claim_now: "Claim", 
        claimed: "Claimed", 
        no_plan: "No Active Plan",
        pending: "Pending", 
        approved: "Approved", 
        rejected: "Rejected",
        gmail_sell: "Gmail Sell", 
        ref_challenge: "Referral Challenge", 
        active_ref: "Active Refs", 
        hold: "Hold", 
        submit_email: "Submit Gmail", 
        today_limit_reached: "Daily limit reached!",
        avg_rate: "Avg Rate", 
        total_sold: "Total Sold", 
        copy_pass: "Copy Pass",
        already_done: "Task already completed!", 
        one_task_limit: "You can only do 1 task per day!",
        target: "Target", 
        reward: "Reward",
        gmail_msg: "Message: When creating Gmail, you must use this password we provided. Password: {pass}",
        gmail_rule_title: "Rules & Regulations",
        gmail_rule_desc: "You can earn by creating Gmails here.<br><br><b>Rules:</b><br>1. You can use any name for the Gmail.<br>2. <b>Important:</b> You MUST use the password we provide below. If you submit a Gmail with a different password, it will be rejected.<br>3. Do NOT use any numbers in the Gmail username (e.g. use 'john.doe@gmail.com' not 'john123@gmail.com'). Only English letters.<br><br>Please follow these instructions carefully to get paid.",
        i_understand: "I Understand",
        recent_sub: "Recent Submissions",
        submit_new_gmail: "Submit New Gmail",
        language: "Language",
        no_plan_found: "No Plan Found",
        withdraw_header: "Withdraw via {method}",
        label_num: "Number",
        label_amt: "Amount",
        ph_num: "Enter Account Number",
        ph_amt: "Enter Amount",
        pay_step2_header: "Send Money To",
        trx_ph: "Transaction ID",
        pending_act: "Activation Pending",
        ref_reward_txt: "Per Referral: {amount}৳",
        min_withdraw_txt: "Minimum Withdraw: {amount}৳",
        copied: "Copied!",
        req_ref_txt: "You need {req} active referrals to withdraw. You have {curr}.",
        sender_phone: "Sender Phone Number",
        sender_phone_ph: "Enter sender phone number",
        screenshot: "Screenshot",
        upload_screenshot: "Upload Screenshot",
        choose_file: "Choose File",
        file_not_selected: "No file selected",
        withdraw_fee: "Withdraw Fee",
        net_amount: "Net Amount",
        fee_info: "Fee will be deducted from your withdraw amount",
        deposit: "Deposit",
        image_too_large: "Image is too large! Maximum size is 5MB",
        processing_image: "Processing image...",
        encryption_complete: "Encryption completed successfully",
        free_activation: "Free Activation",
        email_username_ph: "Email Address or Username",
        task_completed_count: "Completed: {current}/{limit} daily",
        enter_gift_code: "Enter Gift Code",
        apply_code: "Apply Code",
        gift_applied: "Gift code applied successfully! +{amount}৳ added to your balance.",
        invalid_code: "Invalid or expired gift code.",
        code_already_used: "This gift code has already been used.",
        gift_applied_title: "Gift Code Applied!",
    },
    bn: { 
        dashboard: "ড্যাশবোর্ড", 
        task: "টাস্ক", 
        plan: "প্ল্যান", 
        withdraw: "উত্তোলন", 
        history: "হিস্ট্রি", 
        profile: "প্রোফাইল", 
        rules: "নিয়মাবলী", 
        privacy_policy: "গোপনীয়তা নীতি",
        gift_code: "গিফট কোড",
        login: "লগইন", 
        logout: "লগ আউট", 
        welcome: "স্বাগতম", 
        activate: "অ্যাকাউন্ট এক্টিভ করুন", 
        verified: "ভেরিফাইড", 
        inactive: "ইনএ্যাক্টিভ", 
        balance: "ব্যালেন্স", 
        income: "মোট আয়", 
        ref: "রেফারেল", 
        share: "শেয়ার করুন", 
        guest: "অতিথি", 
        no_access: "লগইন প্রয়োজন", 
        no_access_desc: "এই ফিচারটি পেতে লগইন করুন।", 
        act_desc: "টাকা তুলতে অ্যাকাউন্ট এক্টিভ করুন", 
        act_msg: "অ্যাকাউন্ট ইনএ্যাক্টিভ", 
        edit: "এডিট", 
        save: "সেভ", 
        cancel: "বাতিল", 
        trx_id: "ট্রানজেকশন আইডি", 
        submit: "জমা দিন",
        logout_confirm: "আপনি কি নিশ্চিত যে আপনি লগআউট করতে চান?", 
        edit_profile: "প্রোফাইল এডিট",
        create_acc: "অ্যাকাউন্ট তৈরি করুন", 
        already_purchased: "কেনা হয়েছে", 
        buy_now: "এখনই কিনুন",
        loading_rec: "লোডিং...", 
        no_rec: "কোনো তথ্য পাওয়া যায়নি", 
        no_withdraw: "কোনো উত্তোলন পাওয়া যায়নি",
        allow_popup: "পপ-আপ অনুমতি দিন", 
        task_complete: "টাস্ক সম্পন্ন!", 
        insuff_bal: "উত্তোলনের জন্য পর্যাপ্ত ব্যালেন্স নেই!",
        login_title: "লগইন", 
        register_title: "অ্যাকাউন্ট খুলুন", 
        login_ph: "ইমেইল অ্যাড্রেস", 
        pass_ph: "পাসওয়ার্ড", 
        full_name_ph: "পুরো নাম", 
        username_ph: "ইউজারনেম", 
        email_ph: "ইমেইল অ্যাড্রেস", 
        ref_ph: "রেফার কোড (অপশনাল)", 
        confirm_ph: "পাসওয়ার্ড নিশ্চিত করুন",
        next: "পরবর্তী", 
        back: "ফিরে যান", 
        create_acc_btn: "অ্যাকাউন্ট তৈরি করুন", 
        no_account: "অ্যাকাউন্ট নেই?", 
        have_account: "অ্যাকাউন্ট আছে?",
        register_link: "রেজিস্ট্রেশন", 
        login_link: "লগইন",
        select_method: "মেথড সিলেক্ট করুন", 
        send_money: "টাকা পাঠান", 
        method_bkash: "বিকাশ", 
        method_nagad: "নগদ",
        daily_claim: "দৈনিক ক্লেইম", 
        claim_now: "ক্লেইম", 
        claimed: "নেওয়া হয়েছে", 
        no_plan: "কোনো প্ল্যান নেই",
        pending: "পেন্ডিং", 
        approved: "অনুমোদিত", 
        rejected: "বাতিল",
        gmail_sell: "জিমেইল সেল", 
        ref_challenge: "রেফার চ্যালেঞ্জ", 
        active_ref: "এক্টিভ রেফার", 
        hold: "হোল্ডিং", 
        submit_email: "জিমেইল জমা দিন", 
        today_limit_reached: "আজকের লিমিট শেষ!",
        avg_rate: "গড় রেট", 
        total_sold: "মোট বিক্রি", 
        copy_pass: "পাসওয়ার্ড কপি",
        already_done: "টাস্কটি ইতিমধ্যে করা হয়েছে!", 
        one_task_limit: "প্রতিদিন মাত্র ১টি টাস্ক করতে পারবেন!",
        target: "টার্গেট", 
        reward: "পুরষ্কার",
        gmail_msg: "বার্তা: জিমেইল খোলার সময় অবশ্যই আমাদের দেয়া এই পাসওয়ার্ড ব্যবহার করবেন, পাসওয়ার্ড: {pass}",
        gmail_rule_title: "নিয়ম এবং নীতিমালা",
        gmail_rule_desc: "আপনি আমাদের এখানে জিমেইল তৈরি করে প্রতিদিন আয় করতে পারবেন।<br><br><b>নিয়মাবলী:</b><br>১. জিমেইল এর নাম আপনার ইচ্ছামত দিতে পারবেন।<br>২. <b>সতর্কতা:</b> পাসওয়ার্ড যেটি দিবেন সেটি অবশ্যই আমাদের দেয়া এবং নিচে প্রদর্শিত পাসওয়ার্ড হতে হবে। অন্য পাসওয়ার্ড দিলে তা বাতিল হবে।<br><br>৩. জিমেইল ইউজারনেমে কোনো সংখ্যা (123) ব্যবহার করা যাবে না, শুধুমাত্র ইংরেজি অক্ষর ব্যবহার করতে হবে।সঠিকভাবে কাজ করতে নির্দেশনা মেনে চলুন।",
        i_understand: "আমি বুঝেছি",
        recent_sub: "সাম্প্রতিক জমা",
        submit_new_gmail: "নতুন জিমেইল জমা দিন",
        language: "ভাষা",
        no_plan_found: "কোনো প্ল্যান পাওয়া যায়নি",
        withdraw_header: "{method} এর মাধ্যমে উইথড্র করুন",
        label_num: "নাম্বার",
        label_amt: "পরিমাণ",
        ph_num: "অ্যাকাউন্ট নাম্বার দিন",
        ph_amt: "পরিমাণ লিখুন",
        pay_step2_header: "টাকা পাঠান",
        trx_ph: "ট্রানজেকশন আইডি",
        pending_act: "অ্যাক্টিভেশন পেন্ডিং",
        ref_reward_txt: "প্রতি রেফারে: {amount}৳",
        min_withdraw_txt: "সর্বনিম্ন উত্তোলন: {amount}৳",
        copied: "কপি হয়েছে!",
        req_ref_txt: "টাকা তুলতে {req} টি এক্টিভ রেফারের প্রয়োজন। আপনার আছে {curr} টি।",
        sender_phone: "প্রেরকের ফোন নাম্বার",
        sender_phone_ph: "প্রেরকের ফোন নাম্বার লিখুন",
        screenshot: "স্ক্রিনশট",
        upload_screenshot: "স্ক্রিনশট আপলোড করুন",
        choose_file: "ফাইল সিলেক্ট করুন",
        file_not_selected: "কোনো ফাইল সিলেক্ট করা হয়নি",
        withdraw_fee: "উত্তোলন ফি",
        net_amount: "নেট পরিমাণ",
        fee_info: "ফি আপনার উত্তোলনের টাকা থেকে কাটা হবে",
        deposit: "ডিপোজিট",
        image_too_large: "ছবিটি খুব বড়! সর্বোচ্চ সাইজ ৫MB",
        processing_image: "ছবি প্রক্রিয়াকরণ হচ্ছে...",
        encryption_complete: "এনক্রিপশন সফলভাবে সম্পন্ন হয়েছে",
        free_activation: "ফ্রি অ্যাক্টিভেশন",
        email_username_ph: "ইমেইল অ্যাড্রেস অথবা ইউজারনেম",
        task_completed_count: "Completed: {current}/{limit} দৈনিক",
        enter_gift_code: "গিফট কোড লিখুন",
        apply_code: "কোড প্রয়োগ করুন",
        gift_applied: "গিফট কোড সফলভাবে প্রয়োগ করা হয়েছে! আপনার ব্যালেন্সে +{amount}৳ যোগ করা হয়েছে।",
        invalid_code: "অকার্যকর বা মেয়াদোত্তীর্ণ গিফট কোড।",
        code_already_used: "এই গিফট কোডটি ইতিমধ্যে ব্যবহৃত হয়েছে।",
        gift_applied_title: "গিফট কোড প্রয়োগ করা হয়েছে!",
    }
};
